rtabmap:
  ros__parameters:
    # --- Frames ---
    frame_id: base_link
    odom_frame_id: odom
    publish_tf: false            # TF odom->base_link dari EKF saja

    # --- 2D motion ---
    Reg/Force3DoF: true          # kunci ke x-y-yaw

    # --- ICP for high-speed mobile ---
    Odom/Strategy: "0"           # 0=ICP
    Icp/PointToPlane: true
    Icp/VoxelSize: 0.10          # 10 cm; kompromi speed vs detail
    Icp/MaxCorrespondenceDistance: 1.2
    Icp/Iterations: 30
    Icp/Epsilon: 0.0001
    Icp/OutlierRatio: 0.65
    Icp/CorrespondenceRatio: 0.2 # minimal match fraction biar reject scan buruk

    # batas antar frame (mobil @20 Hz)
    Icp/MaxTranslation: 2.0      # m
    Icp/MaxRotation: 0.20        # rad

    # --- Odometry behavior ---
    Odom/GuessMotion: true
    Odom/ResetCountdown: "0"
    Odom/ScanKeyFrameThr: 0.7    # ganti keyframe bila gerak cukup besar (stabilkan ICP)

    # --- Subscriptions (Pandar40 -> PointCloud2) ---
    subscribe_cloud: true
    subscribe_scan_cloud: false

ekf_local_node:
  ros__parameters:
    frequency: 50.0
    two_d_mode: true
    sensor_timeout: 0.2

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    publish_tf: true

    # ============ IMU (RION TL740D) ============
    imu0: /imu/data
    # Hanya yaw & yaw rate yang dipakai untuk 2D; roll/pitch boleh off agar simple
    imu0_config: [ false, false, false,    # px py pz
                   false, false, true,     # roll pitch yaw (pakai yaw)
                   false, false, false,    # vx vy vz
                   false, false, true,     # wx wy wz (pakai yaw rate)
                   false, false, false ]   # ax ay az
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
    imu0_queue_size: 20

    # ============ LiDAR ICP Odometry ============
    odom0: /icp_odom/odom
    odom0_config: [  true,  true,  false,  # px py pz
                     false, false,  true,  # roll pitch yaw
                     true,  true,  false,  # vx vy vz
                     false, false,  true,  # wx wy wz
                     false, false,  false ]
    odom0_differential: false
    odom0_queue_size: 20

    # (OPSIONAL) Wheel speed / vehicle twist dari CAN
    # twist0: /vehicle/twist
    # twist0_config: [ false, false, false,
    #                  false, false, false,
    #                  true,  false, false,   # vx saja
    #                  false, false, false,
    #                  false, false, false ]
    # twist0_queue_size: 20

    # ---- Covariances (start konservatif; tuning di lapangan) ----
    process_noise_covariance: [ 0.10, 0,    0,    0,    0,    0,
                                0,    0.10, 0,    0,    0,    0,
                                0,    0,    1e6,  0,    0,    0,
                                0,    0,    0,    1e6,  0,    0,
                                0,    0,    0,    0,    1e6,  0,
                                0,    0,    0,    0,    0,    0.08 ]
    initial_estimate_covariance: [ 1,0,0, 0,0,0,
                                   0,1,0, 0,0,0,
                                   0,0,1e6, 0,0,0,
                                   0,0,0, 1e6,0,0,
                                   0,0,0, 0,1e6,0,
                                   0,0,0, 0,0,0.5 ]
