camerakiri:
  camera_node:
    ros__parameters:
      video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:1:1.0-video-index0
      camera_info_url: "package://ros2_utils/configs/camera_left_calib.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [640, 480]
      publish_rate: 20

cameratengah:
  camera_node:
    ros__parameters:
      video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:2:1.0-video-index0
      camera_info_url: "package://ros2_utils/configs/camera_center_calib.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [640, 480]
      publish_rate: 20

camerakanan:
  camera_node:
    ros__parameters:
      video_device: /dev/v4l/by-path/pci-0000:00:14.0-usb-0:3:1.0-video-index0
      camera_info_url: "package://ros2_utils/configs/camera_right_calib.yaml"
      pixel_format: "YUYV"
      output_encoding: "yuv422_yuy2"
      image_size: [640, 480]
      publish_rate: 20
